CREATE DATABASE IF NOT EXISTS dimuzica;

USE dimuzica;

CREATE TABLE IF NOT EXISTS usuario(
idUsuario int primary key auto_increment,
nome varchar(30),
email varchar(255) UNIQUE,
senha varchar(255),
genero varchar(20),
check (genero in('alternativo','metal','rock'))
);

CREATE TABLE IF NOT EXISTS musica(
idMusica int primary key auto_increment,
titulo varchar(40),
audio varchar(500) unique,
genero varchar(20),
check (genero in('alternativo','metal','rock'))
);

CREATE TABLE IF NOT EXISTS curtida(
fkUsuario int,
fkMusica int,
primary key (fkUsuario, fkMusica),
foreign key (fkUsuario) references usuario(idUsuario),
foreign key (fkMusica) references musica(idMusica)
);

-- Apague o comentário para inserir
/*
INSERT INTO usuario(nome, email, senha, genero) VALUES
('Alexandre Silva', 'alexandre.silva@email.com', 'Alex@1234', 'rock'),
('Isabela Oliveira', 'isabela.oliveira@email.com', 'Isabela!2024', 'metal'),
('Gustavo Costa', 'gustavo.costa@email.com', 'Gust@vo@123', 'alternativo'),
('Tatiane Pereira', 'tatiane.pereira@email.com', 'T@tiane123', 'rock'),
('Bruno Almeida', 'bruno.almeida@email.com', 'Bruno#1234', 'metal'),
('Carla Rocha', 'carla.rocha@email.com', 'Carla@2024', 'alternativo'),
('Rogério Lima', 'rogerio.lima@email.com', 'Rog@rio567', 'rock'),
('Renata Santos', 'renata.santos@email.com', 'Ren@ta88', 'metal'),
('Simone Martins', 'simone.martins@email.com', 'Simone!2024$', 'alternativo'),
('Fábio Souza', 'fabio.souza@email.com', 'Fabio#2024', 'rock'),
('Cátia Oliveira', 'catia.oliveira@email.com', 'Cat!a1234', 'metal'),
('Maurício Ferreira', 'mauricio.ferreira@email.com', 'Mau!2024', 'alternativo'),
('Natália Rocha', 'natalia.rocha@email.com', 'Nat@lia567', 'rock'),
('Leonardo Costa', 'leonardo.costa@email.com', 'Leo@2024$', 'metal'),
('Gabriela Lima', 'gabriela.lima@email.com', 'Gabriela#88', 'alternativo'),
('Felipe Souza', 'felipe.souza@email.com', 'Felipe!2024', 'rock'),
('Sabrina Martins', 'sabrina.martins@email.com', 'Sabri@2024', 'metal'),
('Jorge Silva', 'jorge.silva@email.com', 'J0rg3@2024', 'alternativo'),
('Luciana Rocha', 'luciana.rocha@email.com', 'Luc!ana123', 'rock'),
('Marco Oliveira', 'marco.oliveira@email.com', 'M@rco2024$', 'metal'),
('Michele Almeida', 'michele.almeida@email.com', 'Mich3l@123', 'alternativo'),
('Juliano Costa', 'juliano.costa@email.com', 'Julian0@2024', 'rock'),
('Viviane Pereira', 'viviane.pereira@email.com', 'Vivi@na2024', 'metal'),
('Eduardo Rocha', 'eduardo.rocha@email.com', 'Eduard0@88', 'alternativo'),
('Thais Silva', 'thais.silva@email.com', 'Th@is1234', 'rock'),
('Ricardo Martins', 'ricardo.martins@email.com', 'Ric@rd0!2024', 'metal'),
('Patrícia Almeida', 'patricia.almeida@email.com', 'P@tricia123', 'alternativo'),
('Daniela Lima', 'daniela.lima@email.com', 'D@niela2024', 'rock'),
('Fernando Costa', 'fernando.costa@email.com', 'F3rnando@123', 'metal'),
('Luciana Santos', 'luciana.santos@email.com', 'L@uciana2024', 'alternativo'),
('Lucas Pereira', 'lucas.pereira@email.com', 'Luca$1234', 'metal'),
('Marta Souza', 'marta.souza@email.com', 'M@rta#2024', 'rock'),
('Roberto Oliveira', 'roberto.oliveira@email.com', 'R0b3rto$123', 'alternativo'),
('Juliana Lima', 'juliana.lima@email.com', 'Juliana@123', 'rock'),
('Carlos Martins', 'carlos.martins@email.com', 'C@rlos#2024', 'metal'),
('Sofia Santos', 'sofia.santos@email.com', 'S0fia@2024', 'alternativo'),
('Tatiane Rocha', 'tatiane.rocha@email.com', 'T@tiane2024!', 'metal'),
('Felipe Costa', 'felipe.costa@email.com', 'Felipe@1234', 'rock'),
('Eduardo Almeida', 'eduardo.almeida@email.com', 'Eduardo!123', 'alternativo'),
('Amanda Ferreira', 'amanda.ferreira@email.com', 'Amanda@!123', 'metal'),
('Rafael Silva', 'rafael.silva@email.com', 'R@fael!2024', 'rock'),
('Gustavo Rocha', 'gustavo.rocha@email.com', 'Gus@tavo123', 'alternativo'),
('Mariana Souza', 'mariana.souza@email.com', 'Mari@na!2024', 'metal'),
('João Costa', 'joao.costa@email.com', 'J0ao@2024#', 'rock'),
('Leonardo Pereira', 'leonardo.pereira@email.com', 'Leo@12345', 'alternativo'),
('Juliano Almeida', 'juliano.almeida@email.com', 'Juli@no2024$', 'rock'),
('Ricardo Lima', 'ricardo.lima@email.com', 'Ric@rdo1234', 'alternativo'),
('Carla Santos', 'carla.santos@email.com', 'Carla!@123', 'metal'),
('Felipe Martins', 'felipe.martins@email.com', 'Felipe@!2024', 'rock'),
('Patrícia Rocha', 'patricia.rocha@email.com', 'P@tricia1234', 'alternativo'),
('Marcos Ferreira', 'marcos.ferreira@email.com', 'Marcos@123', 'metal'),
('Luciana Costa', 'luciana.costa@email.com', 'Luc!ana2024', 'rock'),
('Simone Almeida', 'simone.almeida@email.com', 'S1mone@2024', 'alternativo'),
('José Silva', 'jose.silva@email.com', 'J0s3@!2024', 'metal'),
('Kátia Lima', 'katia.lima@email.com', 'K@tia2024$', 'rock'),
('Fabiana Rocha', 'fabiana.rocha@email.com', 'F@bi!ana2024', 'alternativo'),
('Fernanda Oliveira', 'fernanda.oliveira@email.com', 'F3rnanda@123', 'metal'),
('André Costa', 'andre.costa@email.com', 'Andr3@1234', 'rock'),
('Tatiane Martins', 'tatiane.martins@email.com', 'T@tiane$2024', 'alternativo'),
('Marcio Silva', 'marcio.silva@email.com', 'M@rcio!2024', 'metal'),
('Sérgio Pereira', 'sergio.pereira@email.com', 'S3rgio@2024', 'rock'),
('Amanda Rocha', 'amanda.rocha@email.com', 'Amand@123', 'alternativo'),
('Flávio Oliveira', 'flavio.oliveira@email.com', 'Flav!o1234', 'metal'),
('Tânia Martins', 'tania.martins@email.com', 'T@nia2024', 'rock'),
('Márcio Costa', 'marcio.costa@email.com', 'M@rcio123', 'alternativo'),
('Sandra Silva', 'sandra.silva@email.com', 'S@ndra!2024', 'metal');

insert into musica values
(default, 'The adults are talking', 'https://open.spotify.com/embed/track/5ruzrDWcT0vuJIOMW7gMnW?utm_source=generator', 'alternativo'),
(default, 'Reptilia','https://open.spotify.com/embed/track/57Xjny5yNzAcsxnusKmAfA?utm_source=generator','alternativo'),
(default, 'Creep', 'https://open.spotify.com/embed/track/70LcF31zb1H0PyJoS1Sx1r?utm_source=generator', 'alternativo'),
(default, 'Karma police','https://open.spotify.com/embed/track/63OQupATfueTdZMWTxW03A?utm_source=generator', 'alternativo'),
(default, 'Fool', 'https://open.spotify.com/embed/track/5PQwmOZwMhhV8q8QMpCRAZ?utm_source=generator', 'alternativo'),
(default, 'Starman', 'https://open.spotify.com/embed/track/0pQskrTITgmCMyr85tb9qq?utm_source=generator', 'alternativo'),
(default, 'Heart Shaped Box', 'https://open.spotify.com/embed/track/11LmqTE2naFULdEP94AUBa?utm_source=generator', 'alternativo'),
(default, 'The Man Who Sold The World', 'https://open.spotify.com/embed/track/15VRO9CQwMpbqUYA7e6Hwg?utm_source=generator','alternativo'),
(default, 'There Is a Light That Never Goes Out', 'https://open.spotify.com/embed/track/0WQiDwKJclirSYG9v5tayI?utm_source=generator', 'alternativo'),
(default, "Heaven Knows I'm Miserable Now", 'https://open.spotify.com/embed/track/1H5N26VqHR4JhuaRKY2I0u?utm_source=generator', 'alternativo'),
(default, "Boys Don't Cry", 'https://open.spotify.com/embed/track/1QFh8OH1e78dGd3VyJZCAC?utm_source=generator', 'alternativo'),
(default, 'Lovesong', 'https://open.spotify.com/embed/track/2mIrfke7vosXAEWfz6ucyo?utm_source=generator','alternativo'),
(default, 'Until I know','https://open.spotify.com/embed/track/4KH9g027K949LR2xkjC4jk?utm_source=generator','alternativo'),
(default, 'When You Sleep','https://open.spotify.com/embed/track/2KylN9C0wNbzLgZNTG9oiU?utm_source=generator','alternativo'),
(default, 'Buddy HolLy','https://open.spotify.com/embed/track/3mwvKOyMmG77zZRunnxp9E?utm_source=generator', 'alternativo'),
(default, "Say It Ain't So", 'https://open.spotify.com/embed/track/6VoIBz0VhCyz7OdEoRYDiA?utm_source=generator', 'alternativo'),
(default, 'Feel Good Inc.', 'https://open.spotify.com/embed/track/0d28khcov6AiegSCpG5TuT?utm_source=generator','alternativo'),
(default, 'Clint Eastwood', 'https://open.spotify.com/embed/track/1RKUoGiLEbcXN4GY4spQDx?utm_source=generator','alternativo'),
(default, 'No one knows', 'https://open.spotify.com/embed/track/6y20BV5L33R8YXM0YuI38N?utm_source=generator', 'rock'),
(default, 'Bohemian Rhapsody', 'https://open.spotify.com/embed/track/3z8h0TU7ReDPLIbEnYhWZb?utm_source=generator', 'rock'),
(default, 'Come together', 'https://open.spotify.com/embed/track/2EqlS6tkEnglzr7tkKAAYD?utm_source=generator', 'rock'),
(default, 'The Chain', 'https://open.spotify.com/embed/track/5e9TFTbltYBg2xThimr0rU?utm_source=generator', 'rock'),
(default, 'Like A Stone', 'https://open.spotify.com/embed/track/3YuaBvuZqcwN3CEAyyoaei?utm_source=generator', 'rock'),
(default, "Sweet Child O' Mine", 'https://open.spotify.com/embed/track/7snQQk1zcKl8gZ92AnueZW?utm_source=generator','rock'),
(default, 'Thunderstruck', 'https://open.spotify.com/embed/track/57bgtoPSgt236HzfBOd8kj?utm_source=generator', 'rock'),
(default, "I Was Made For Lovin' You", 'https://open.spotify.com/embed/track/07q0QVgO56EorrSGHC48y3?utm_source=generator','rock'),
(default, 'Even Flow','https://open.spotify.com/embed/track/6QewNVIDKdSl8Y3ycuHIei?utm_source=generator', 'rock'),
(default, 'Everlong','https://open.spotify.com/embed/track/5UWwZ5lm5PKu6eKsHAGxOk?utm_source=generator','rock'),
(default, 'How you remind me', 'https://open.spotify.com/embed/track/0gmbgwZ8iqyMPmXefof8Yf?utm_source=generator', 'rock'),
(default, 'Wait and bleed', 'https://open.spotify.com/embed/track/2gscB6kDOmrv1P6qs2KXE3?utm_source=generator', 'metal'),
(default, 'Duality', 'https://open.spotify.com/embed/track/61mWefnWQOLf90gepjOCb3?utm_source=generator','metal'),
(default, 'Psychosocial', 'https://open.spotify.com/embed/track/3RAFcUBrCNaboRXoP3S5t1?utm_source=generator','metal'),
(default, 'Toxicity','https://open.spotify.com/embed/track/0snQkGI5qnAmohLE7jTsTn?utm_source=generator','metal'),
(default, 'Chop Suey!', 'https://open.spotify.com/embed/track/2DlHlPMa4M17kufBvI2lEN?utm_source=generator','metal'),
(default, 'Break Stuff','https://open.spotify.com/embed/track/5cZqsjVs6MevCnAkasbEOX?utm_source=generator','metal'),
(default, "Rollin'", 'https://open.spotify.com/embed/track/3IV4swNduIRunHREK80owz?utm_source=generator','metal'),
(default, 'In the End','https://open.spotify.com/embed/track/60a0Rd6pjrkxjPbaKzXjfq?utm_source=generator','metal'),
(default, 'Numb','https://open.spotify.com/embed/track/2nLtzopw4rPReszdYBJU6h?utm_source=generator','metal'),
(default, 'Faint','https://open.spotify.com/embed/track/4Yf5bqU3NK4kNOypcrLYwU?utm_source=generator','metal'),
(default, 'Freak On A Leash', 'https://open.spotify.com/embed/track/6W21LNLz9Sw7sUSNWMSHRu?utm_source=generator','metal'),
(default, 'Coming Undone','https://open.spotify.com/embed/track/3o7TMr6RmIusYH7Kkg7ujR?utm_source=generator','metal'),
(default, 'Falling Away From Me','https://open.spotify.com/embed/track/2F6FfZ4w8z3eJpSxPotVO5?utm_source=generator','metal'),
(default, 'Going Under','https://open.spotify.com/embed/track/3UygY7qW2cvG9Llkay6i1i?utm_source=generator','metal'),
(default, 'Change','https://open.spotify.com/embed/track/51c94ac31swyDQj9B3Lzs3?utm_source=generator','metal'),
(default, 'My Own Summer (Shove It)','https://open.spotify.com/embed/track/1158ckiB5S4cpsdYHDB9IF?utm_source=generator','metal'),
(default, 'Be Quiet And Drive (Far Away)', 'https://open.spotify.com/embed/track/4Uiw0Sl9yskBaC6P4DcdVD?utm_source=generator','metal'),
(default, 'Dragula','https://open.spotify.com/embed/track/6Nm8h73ycDG2saCnZV8poF?utm_source=generator','metal'),
(default, 'Stranded','https://open.spotify.com/embed/track/60fUDmIWuKhngaeBIVhqIV?utm_source=generator','metal'),
(default, 'Bodies','https://open.spotify.com/embed/track/7CpbhqKUedOIrcvc94p60Y?utm_source=generator','metal'),
(default, 'Last Resort','https://open.spotify.com/embed/track/5W8YXBz9MTIDyrpYaCg2Ky?utm_source=generator','metal'),
(default, 'Kingslayer', 'https://open.spotify.com/embed/track/7CAbF0By0Fpnbiu6Xn5ZF7?utm_source=generator','metal'),
(default, 'Snot', 'https://open.spotify.com/embed/track/3qCQNtggJw1gxoptMgDhyR?utm_source=generator','metal'),
(default, 'Down With The Sickness','https://open.spotify.com/embed/track/4ImIJRZNJhNQLLdUFSYJoS?utm_source=generator','metal'),
(default, 'Happy?','https://open.spotify.com/embed/track/0INUE1K7cEiE8VH63Rv5RJ?utm_source=generator','metal');

INSERT INTO curtida VALUES
(1, 5),
(1, 12),
(1, 21),
(2, 3),
(2, 14),
(2, 18),
(2, 22),
(3, 7),
(3, 17),
(3, 26),
(4, 2),
(4, 10),
(4, 19),
(5, 4),
(5, 9),
(5, 15),
(5, 23),
(6, 11),
(6, 25),
(7, 6),
(7, 8),
(7, 16),
(7, 20),
(8, 1),
(8, 13),
(9, 6),
(9, 14),
(9, 24),
(10, 3),
(10, 12),
(10, 19),
(10, 21),
(11, 5),
(11, 15),
(11, 18),
(12, 2),
(12, 9),
(12, 22),
(12, 25),
(13, 4),
(13, 11),
(13, 16),
(14, 7),
(14, 10),
(14, 26),
(15, 6),
(15, 13),
(15, 20),
(15, 23),
(16, 8),
(16, 14),
(16, 18),
(17, 12),
(17, 19),
(17, 25),
(18, 1),
(18, 9),
(18, 22),
(19, 3),
(19, 17),
(19, 26),
(20, 7),
(20, 13),
(20, 21),
(21, 2),
(21, 8),
(21, 16),
(21, 24),
(22, 5),
(22, 12),
(22, 19),
(22, 23),
(23, 6),
(23, 11),
(23, 18),
(23, 20),
(24, 4),
(24, 9),
(24, 15),
(24, 26),
(25, 10),
(25, 17),
(25, 22),
(26, 1),
(26, 8),
(26, 18),
(27, 3),
(27, 13),
(27, 25),
(28, 7),
(28, 12),
(28, 19),
(29, 9),
(29, 14),
(29, 24),
(30, 5),
(30, 10),
(30, 18),
(30, 26),
(31, 6),
(31, 13),
(31, 21),
(32, 3),
(32, 8),
(32, 20),
(33, 2),
(33, 16),
(33, 23),
(34, 5),
(34, 11),
(34, 19),
(35, 4),
(35, 9),
(35, 12),
(35, 25),
(36, 6),
(36, 18),
(36, 22),
(37, 1),
(37, 10),
(37, 14),
(38, 7),
(38, 13),
(38, 16),
(39, 2),
(39, 5),
(39, 19),
(40, 3),
(40, 11),
(40, 26),
(41, 6),
(41, 9),
(41, 20),
(42, 8),
(42, 17),
(42, 21),
(43, 1),
(43, 4),
(43, 15),
(44, 7),
(44, 14),
(44, 23),
(45, 5),
(45, 12),
(45, 19),
(46, 3),
(46, 11),
(46, 18),
(47, 6),
(47, 13),
(47, 22),
(48, 2),
(48, 9),
(48, 25),
(49, 10),
(49, 15),
(49, 26),
(50, 4),
(50, 13),
(50, 20),
(51, 6),
(51, 9),
(51, 17),
(52, 1),
(52, 11),
(52, 23),
(53, 3),
(53, 7),
(53, 12),
(54, 5),
(54, 14),
(54, 21),
(55, 8),
(55, 15),
(55, 19),
(56, 2),
(56, 6),
(56, 26),
(57, 1),
(57, 12),
(57, 17),
(58, 4),
(58, 10),
(58, 23),
(59, 5),
(59, 13),
(59, 20),
(60, 8),
(60, 16),
(60, 19),
(61, 9),
(61, 14),
(61, 24),
(62, 7),
(62, 11),
(62, 22),
(63, 3),
(63, 15),
(63, 25),
(64, 6),
(64, 12),
(64, 18),
(65, 2),
(65, 10),
(65, 13),
(66, 4),
(66, 8),
(66, 26),
(67, 3),
(67, 17),
(67, 20),
(68, 9),
(68, 15),
(68, 19),
(69, 7),
(69, 13),
(69, 22),
(70, 6),
(70, 10);
*/

SELECT genero,count(genero) as 'qtd' FROM usuario GROUP BY genero;

SELECT titulo, count(fkMusica) FROM curtida JOIN musica ON fkMusica = idMusica
GROUP BY titulo;

SELECT * FROM musica;

SELECT * FROM usuario;
